version: "3"
services:

  nginx:
    image: nginx:1.13.9-alpine
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.type=worker]
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./nginx:/var/log/nginx"

  php:
    build: ./php
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.type=worker]
      restart_policy:
        condition: on-failure
    ports:
      - 9000:9000
    networks:
      - webnet
    volumes:
      - "./public:/var/www"

  db:
    image: percona:5.7
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.type=db]
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - webnet

  adminer:
    image: adminer:fastcgi
    ports:
      - 8080:8080
    networks:
      - webnet

networks:
  webnet: